name: Test Suite

on:
  push:
  pull_request:

jobs:
  php_tests:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [8.2, 8.3]
        laravel: [11.*]
        stability: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest]
        include:
          - os: windows-latest
            php: 8.3
            laravel: 11.*
            stability: prefer-stable
          - os: windows-latest
            php: 8.4
            laravel: 11.*
            stability: prefer-stable

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-suggest

      - name: Run PHPUnit
        run: vendor/bin/phpunit
